const LinkData: any[] = [
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 1,
    "courseName": "应用市场介绍",
    "imageUrl": $r('app.media.cola'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 2,
    "courseName": "上架流程",
    "imageUrl": $r('app.media.cola'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 3,
    "courseName": "应用出海",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 4,
    "courseName": "审核政策",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 5,
    "courseName": "CaaS Kit - HMS Core精品实战课",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 6,
    "courseName": "机器学习在图像分割场景中的应用",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 7,
    "courseName": "一分钟了解华为应用内支付服务",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 1,
    "superName": "热门课程",
    "id": 8,
    "courseName": "一分钟了解华为位置服务",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 9,
    "courseName": "Excel函数在商业中的应用",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 10,
    "courseName": "“震动”手机锁屏制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 11,
    "courseName": "“流体动效”手机锁屏制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 12,
    "courseName": "HUAWEI GT自定义表盘制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 13,
    "courseName": "商务表盘制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 14,
    "courseName": "5分钟了解跨应用、跨形态无缝登录",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 15,
    "courseName": "oCPC进阶功能及最新政策解读",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 2,
    "superName": "最新课程",
    "id": 16,
    "courseName": "HUAWEI Ads 游戏行业投放指南",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 17,
    "courseName": "HarmonyOS物联网开发课程",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 18,
    "courseName": "【Hello系列直播课】第1期：手把手教你搭建开发环境",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 19,
    "courseName": "HarmonyOS技术训练营-10分钟快速体验HarmonyOS分布式应用",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 20,
    "courseName": "应用开发基础：JS FA开发基础（第一期）",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 21,
    "courseName": "HarmonyOS Connect设备开发基础：OpenHarmony基础",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 3,
    "superName": "HarmonyOS",
    "id": 22,
    "courseName": "组件开发和集成：SDK集成指南（第五期）",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "courseName": "HUAWEI Developer Day•2018北京精彩回顾",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 24,
    "courseName": "华为AR帮你轻松打造酷炫应用",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 25,
    "courseName": "ARVR应用创新大赛获奖作品",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 26,
    "courseName": "华为HiLink智能家居生态介绍",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 27,
    "courseName": "华为校园千帆行丨武汉站",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 4,
    "superName": "精彩活动",
    "id": 28,
    "courseName": "HUAWEI Developer Day•杭州站精彩回顾",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 29,
    "courseName": "优秀实践分享 - 掌阅科技",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 30,
    "courseName": "极限试驾",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 31,
    "courseName": "AR狙击手",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 32,
    "courseName": "宇宙解码",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 33,
    "courseName": "Wars of Stone",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 34,
    "courseName": "ROCK ME",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 5,
    "superName": "开发者说",
    "id": 35,
    "courseName": "神奇AR智能宝宝",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 36,
    "courseName": "从零开始学架构",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 37,
    "courseName": "架构设计之异步化技术",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 38,
    "courseName": "架构设计之页面静态化技术",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 39,
    "courseName": "Python极简入门",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 40,
    "courseName": "Python实践指南",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 41,
    "courseName": "Java高级特性",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 6,
    "superName": "后端开发",
    "id": 42,
    "courseName": "C++核心编程",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 43,
    "courseName": "EMUI 9.1主题转10.0主题适配指导",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 44,
    "courseName": "“流体动效”手机锁屏制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 7,
    "superName": "移动开发",
    "id": 45,
    "courseName": "“震动”手机锁屏制作",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 46,
    "courseName": "DevOps新技术入门",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 47,
    "courseName": "Vue.js 框架开发系列课程",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 48,
    "courseName": "jQuery实例精讲",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 49,
    "courseName": "JavaScript 编程技巧与实战",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 50,
    "courseName": "基于 Bootstrap 框架开发技巧实战",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 51,
    "courseName": "Java Web开发课程",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 52,
    "courseName": "JavaScript 设计模式",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 53,
    "courseName": "HTML入门基础系列课程",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 54,
    "courseName": "前端系列第7期-微前端–架构介绍篇",
    "imageUrl": $r('app.media.icon'),
  },
  {
    "superId": 8,
    "superName": "前端开发",
    "id": 55,
    "courseName": "Web安全系列课程",
    "imageUrl": $r('app.media.icon'),
  }
]

class TabItem {
  position: number;
  superName: string;

  constructor(position: number, superName: string) {
    this.position = position
    this.superName = superName
  }
}

class CourseItem {
  tag: boolean;
  index: number;
  courseName: string;
  imageUrl: string;

  constructor( index: number, courseName: string, imageUrl: string) {
    this.index = index
    this.courseName = courseName
    this.imageUrl = imageUrl
  }
}

class LinkDataItem {
  tabArray: Array<TabItem> = [] // 课程分类数据
  listArray: Array<CourseItem> = [] //课程数据
  constructor(tabArray: Array<TabItem>, listArray: Array<CourseItem>) {
    this.tabArray = tabArray;
    this.listArray = listArray;
  }
}

function getLinkData(): LinkDataItem {
  let linkDataitem = new LinkDataItem([], []);
  let superId: number = 0
  LinkData.forEach(item => {
    //
    if (superId != item.superId) {
      // 添加课程类别
      let tabItem = new TabItem(linkDataitem.listArray.length, item.superName);
      linkDataitem.tabArray.push(tabItem)
    }
    //添加课程
    let courseItem = new CourseItem(linkDataitem.tabArray.length-1,item.courseName, item.imageUrl)
    linkDataitem.listArray.push(courseItem)
    console.debug(JSON.stringify(linkDataitem.listArray))
    superId = item.superId
  })
  return linkDataitem
}



export { TabItem, CourseItem,getLinkData }